const HOME_TITLE = 'home';
const CHARACTER_SECTION_TITLE = 'characters';
const WORLD_SECTION_TITLE = 'worlds';
const SHIPS_SECTION_TITLE = 'ships';

export default Object.freeze({
  HOME_TITLE: HOME_TITLE,
  CHARACTER_SECTION_TITLE: CHARACTER_SECTION_TITLE,
  WORLD_SECTION_TITLE: WORLD_SECTION_TITLE,
  SHIPS_SECTION_TITLE: SHIPS_SECTION_TITLE
})